print("""lkjrwehtifueywsfr84er7tu954etuy98e87erw5uy98745763t984er6ytiufdrhguieratgluthfsiugkyesa6gyiutd6yufdi7iuldlxux;
      hdslkjfhjdsjkhfjdgfkjhsjfkjdshfkjdhskjfhdshfjkhdfjdshfjdshkjfhdsjfhdshfjdskhfkjdshfkjdshfjdshfjdshfjdshfjkdshfkjhds
      kdjfdshfkdshfkjhdjskfkjdshfkjdshfkjdshfkjdshfkjdshfjdshfkjdshfkjdshbfkjdshfbdsfkjdsnbfkjsdhfkjsdhfkjdshfjkdshfkjdshfkjdsh
      fldsjfdsjfkldsjflkjdsklfkdsfjdjfkdsjflkdsjfdlksjflkdsjfkdsjfksdjkfjdskfjkdsfjkldsjfkdsjfkldsjfkldsjflkdsjl
      jfjfjfjfjfjjfjfkdsjfdsfkdsjlkfjdslkfjlkdsjflkdsjgflkfdshlkjgfh lkfdshglkjbtsakukukukukuihtlrneytwaciuecwyociewwoyecaoy
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa980er7wayrbvcoiewayrioycycycycycycycycycycycycycycycycycycycycycycycycycycycycycycycycycycycyci
      kjfckjfckjfckjfckjfckjfckjfckjfckjfckjfckjfckjfckjfckjfckjfckjfckjfckjfckjfckjfckjfckjfckjfckjfckjfckjfckjfckjfckjfckjfckjfckjfckjfckjfckjfckjfckjfckjfckjfckjfckjfckjfckjfckjfckjfckjfckjfckjfckjfckjfckjfckjfckjfckjfckjfckjfckjfckjfckjfckjfckjfckjfckjfckjfckjfckjfckjfckjfckjfckjfckjfckjfckjfckjfckjfckjfckjfckjfckjfckjfckjfckjfckjfcI""")